from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass(frozen=True)
class Task:
    id: int
    files: list[str]
    instruction: str
    type: str
    # Feature 4: read-only reference files Aider may consult but will not modify.
    context_files: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class AiderContext:
    """Per-task runtime context injected into every Aider message.

    Gives Aider the full picture: what the overall goal is, where this task
    sits in the sequence, and what was already completed — so each task is
    never treated in isolation.
    """

    goal: str
    task_number: int
    total_tasks: int
    completed_summaries: list[str]  # e.g. ["[1] create GameColor.cs"]


@dataclass(frozen=True)
class SubTask:
    """A micro-task generated by the supervisor to fix a mechanical validation failure.

    Sub-tasks target the same files as the parent task and carry atomic
    correction instructions. They are executed before the parent task is
    retried and are NOT sent to the supervisor for review — they are
    structural fixes only (syntax, missing imports, wrong file location).
    """

    parent_id: int
    step: int
    instruction: str
    files: list[str]
    type: str = "modify"

    @property
    def id(self) -> int:
        """Synthetic ID: parent_id * 1000 + step (e.g. task 3 step 2 → 3002)."""
        return self.parent_id * 1000 + self.step


@dataclass(frozen=True)
class SelectedFiles:
    existing: list[Path]
    missing: list[Path]
    all_paths: list[Path]


@dataclass(frozen=True)
class ExecutionResult:
    task_id: int
    succeeded: bool
    exit_code: int
    stdout: str
    stderr: str
    command: list[str]
    attempt_number: int = 1
    duration_seconds: float = 0.0


@dataclass(frozen=True)
class ValidationResult:
    task_id: int
    succeeded: bool
    message: str
    stdout: str
    stderr: str


@dataclass(frozen=True)
class TaskReport:
    """Snapshot of a completed task sent to the supervisor for review.

    Contains the task definition, Aider's execution result, and the git diff
    so the supervisor can make an informed PASS or REWORK decision.
    """

    task: Task
    execution_result: ExecutionResult
    diff: str


@dataclass(frozen=True)
class ReviewResult:
    """The supervisor's verdict on a completed task.

    verdict is either "PASS" (approved) or "REWORK" (rejected with new instruction).
    new_instruction is only populated when verdict == "REWORK".
    """

    task_id: int
    verdict: str
    new_instruction: Optional[str]
    message: str


@dataclass(frozen=True)
class BridgeConfig:
    goal: str
    repo_root: Path
    dry_run: bool
    max_plan_attempts: int
    max_task_retries: int
    validation_command: Optional[str]
    supervisor_command: str
    aider_command: str
    aider_model: Optional[str]
    idea_file: Optional[Path]
    idea_text: Optional[str]
    plan_output_file: Optional[Path]
    task_timeout_seconds: int = 300
    aider_no_map: bool = False
    auto_approve: bool = False  # skip supervisor review; use mechanical validation only
    auto_split_threshold: int = 0  # 0 = disabled; N = split tasks with N+ files into single-file sub-tasks
